### ISSUE TITLE
The module throw an error with i18n

### ISSUE THREAD

**Issue by RomainMarecat** [cstefanache/angular2-img-cropper#158]
The module throw an error i18n with this command line.  
@angular/cli: 1.0.0
node: 7.7.4
os: linux x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0
@angular/compiler-cli: 2.4.10

```
npm run i18n

> ng-xi18n -p src/tsconfig.app.json

Error: ENOENT: no such file or directory, open '/home/romainmarecat/var/www/zeeadmin/out-tsc/app/node_modules/ng2-img-cropper/src/model/point.metadata.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1316:33)
    at MetadataWriterHost.writeMetadata (/home/romainmarecat/var/www/zeeadmin/node_modules/@angular/tsc-wrapped/src/compiler_host.js:164:22)
    at MetadataWriterHost.writeFile (/home/romainmarecat/var/www/zeeadmin/node_modules/@angular/tsc-wrapped/src/compiler_host.js:143:19)
    at Object.writeFile (/home/romainmarecat/var/www/zeeadmin/node_modules/typescript/lib/typescript.js:45369:132)
    at Object.writeFile (/home/romainmarecat/var/www/zeeadmin/node_modules/typescript/lib/typescript.js:7602:14)
    at writeEmittedFiles (/home/romainmarecat/var/www/zeeadmin/node_modules/typescript/lib/typescript.js:37859:20)
    at doEmit (/home/romainmarecat/var/www/zeeadmin/node_modules/typescript/lib/typescript.js:37719:17)
    at emitFile (/home/romainmarecat/var/www/zeeadmin/node_modules/typescript/lib/typescript.js:44665:21)
    at onSingleFileEmit (/home/romainmarecat/var/www/zeeadmin/node_modules/typescript/lib/typescript.js:7569:13)
Extraction failed

```

**Comment by cstefanache** [comment]
Can you please check with 0.8.4?
point.metadata.json - not present in the package. 
Closing for now - reopen if still reproduces
