### ISSUE TITLE
Unable To Install Any Version Later Than 0.0.3 From NPM

### ISSUE THREAD

**Issue by ghost** [cstefanache/angular2-img-cropper#231]
When I run the command `npm install ng2-image-cropper`, the version NPM gives me as the "latest" version is version 0.0.3. I then tried to install version 0.7.6 directly with the command `npm install ng2-image-cropper@0.7.6`, and I got an error message which said:
```
npm ERR! notarget No compatible version found: ng2-image-cropper@0.7.6
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.1, 0.0.2, 0.0.3
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
Based on that error message, it looks like the NPM registry doesn't recognize any versions of ng2-image-cropper other than version 0.0.1, 0.0.2, or 0.0.3. As a result, I have no way of installing the latest version of ng2-image-cropper. Can you please look into this and see why NPM won't resolve any version of ng2-image-cropper later than 0.0.3?

NOTE: I am copying and pasting a redacted copy of my `npm-debug.log` file which was generated when I tried to install ng2-image-cropper version 0.7.6 directly with the command `npm install ng2-image-cropper@0.7.6`:
```
1 verbose cli   'install',
1 verbose cli   'ng2-image-cropper@0.7.6' ]
2 info using npm@4.1.2
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData ng2-image-cropper@0.7.6
8 silly fetchNamedPackageData ng2-image-cropper
9 silly mapToRegistry name ng2-image-cropper
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'ng2-image-cropper',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'ng2-image-cropper',
12 silly mapToRegistry   name: 'ng2-image-cropper',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/ng2-image-cropper
14 verbose request uri https://registry.npmjs.org/ng2-image-cropper
15 verbose request no auth needed
16 info attempt registry request try #1 at 5:42:54 PM
17 verbose request id c90649eed0c70a63
18 verbose etag W/"58d3d620-37e3"
19 verbose lastModified Thu, 23 Mar 2017 14:05:20 GMT
20 http request GET https://registry.npmjs.org/ng2-image-cropper
21 http 304 https://registry.npmjs.org/ng2-image-cropper
22 verbose headers { date: 'Tue, 22 Aug 2017 21:42:58 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"58d3d620-37e3"',
22 verbose headers   age: '55',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-dfw1845-DFW',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1503438179.603829,VS0,VE1',
22 verbose headers   vary: 'Accept-Encoding, Accept' }
23 silly get cb [ 304,
23 silly get   { date: 'Tue, 22 Aug 2017 21:42:58 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"58d3d620-37e3"',
23 silly get     age: '55',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-dfw1845-DFW',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1503438179.603829,VS0,VE1',
23 silly get     vary: 'Accept-Encoding, Accept' } ]
24 verbose etag https://registry.npmjs.org/ng2-image-cropper from cache
25 verbose get saving ng2-image-cropper to \npm-cache\registry.npmjs.org\ng2-image-cropper\.cache.json
27 silly pickManifestFromRegistryMetadata spec 0.7.6 tag latest versions [ '0.0.1', '0.0.2', '0.0.3' ]
28 silly fetchNamedPackageData No valid target from cache, forcing network
29 verbose request uri https://registry.npmjs.org/ng2-image-cropper
30 verbose request no auth needed
31 info attempt registry request try #1 at 5:42:58 PM
32 http request GET https://registry.npmjs.org/ng2-image-cropper
33 http 200 https://registry.npmjs.org/ng2-image-cropper
34 verbose headers { server: 'nginx/1.10.3',
34 verbose headers   'content-type': 'application/json',
34 verbose headers   'last-modified': 'Thu, 23 Mar 2017 14:05:20 GMT',
34 verbose headers   etag: 'W/"58d3d620-37e3"',
34 verbose headers   'content-encoding': 'gzip',
34 verbose headers   'cache-control': 'max-age=300',
34 verbose headers   'content-length': '3778',
34 verbose headers   'accept-ranges': 'bytes',
34 verbose headers   date: 'Tue, 22 Aug 2017 21:42:58 GMT',
34 verbose headers   via: '1.1 varnish',
34 verbose headers   age: '55',
34 verbose headers   connection: 'keep-alive',
34 verbose headers   'x-served-by': 'cache-dfw1845-DFW',
34 verbose headers   'x-cache': 'HIT',
34 verbose headers   'x-cache-hits': '2',
34 verbose headers   'x-timer': 'S1503438179.720788,VS0,VE0',
34 verbose headers   vary: 'Accept-Encoding, Accept' }
35 silly get cb [ 200,
35 silly get   { server: 'nginx/1.10.3',
35 silly get     'content-type': 'application/json',
35 silly get     'last-modified': 'Thu, 23 Mar 2017 14:05:20 GMT',
35 silly get     etag: 'W/"58d3d620-37e3"',
35 silly get     'content-encoding': 'gzip',
35 silly get     'cache-control': 'max-age=300',
35 silly get     'content-length': '3778',
35 silly get     'accept-ranges': 'bytes',
35 silly get     date: 'Tue, 22 Aug 2017 21:42:58 GMT',
35 silly get     via: '1.1 varnish',
35 silly get     age: '55',
35 silly get     connection: 'keep-alive',
35 silly get     'x-served-by': 'cache-dfw1845-DFW',
35 silly get     'x-cache': 'HIT',
35 silly get     'x-cache-hits': '2',
35 silly get     'x-timer': 'S1503438179.720788,VS0,VE0',
35 silly get     vary: 'Accept-Encoding, Accept' } ]
36 verbose get saving ng2-image-cropper to \npm-cache\registry.npmjs.org\ng2-image-cropper\.cache.json
38 silly pickManifestFromRegistryMetadata spec 0.7.6 tag latest versions [ '0.0.1', '0.0.2', '0.0.3' ]
39 silly fetchPackageMetaData Error: No compatible version found: ng2-image-cropper@0.7.6
39 silly fetchPackageMetaData Valid install targets:
39 silly fetchPackageMetaData 0.0.1, 0.0.2, 0.0.3
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (\npm\node_modules\npm\lib\fetch-package-metadata.js:158:16)
39 silly fetchPackageMetaData     at \npm\node_modules\npm\node_modules\iferr\index.js:13:50
39 silly fetchPackageMetaData     at \npm\node_modules\npm\lib\utils\pulse-till-done.js:20:8
39 silly fetchPackageMetaData     at saved (\npm\node_modules\npm\lib\cache\caching-client.js:174:7)
39 silly fetchPackageMetaData     at \npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:261:18
39 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15)
39 silly fetchPackageMetaData  error for ng2-image-cropper@0.7.6 { Error: No compatible version found: ng2-image-cropper@0.7.6
39 silly fetchPackageMetaData Valid install targets:
39 silly fetchPackageMetaData 0.0.1, 0.0.2, 0.0.3
39 silly fetchPackageMetaData
39 silly fetchPackageMetaData     at pickVersionFromRegistryDocument (\npm\node_modules\npm\lib\fetch-package-metadata.js:158:16)
39 silly fetchPackageMetaData     at \npm\node_modules\npm\node_modules\iferr\index.js:13:50
39 silly fetchPackageMetaData     at \npm\node_modules\npm\lib\utils\pulse-till-done.js:20:8
39 silly fetchPackageMetaData     at saved (\npm\node_modules\npm\lib\cache\caching-client.js:174:7)
39 silly fetchPackageMetaData     at \npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:261:18
39 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:123:15) code: 'ETARGET' }
40 silly rollbackFailedOptional Starting
41 silly rollbackFailedOptional Finishing
42 silly runTopLevelLifecycles Finishing
43 silly install printInstalled
44 verbose stack Error: No compatible version found: ng2-image-cropper@0.7.6
44 verbose stack Valid install targets:
44 verbose stack 0.0.1, 0.0.2, 0.0.3
44 verbose stack
44 verbose stack     at pickVersionFromRegistryDocument (\npm\node_modules\npm\lib\fetch-package-metadata.js:158:16)
44 verbose stack     at \npm\node_modules\npm\node_modules\iferr\index.js:13:50
44 verbose stack     at \npm\node_modules\npm\lib\utils\pulse-till-done.js:20:8
44 verbose stack     at saved (\npm\node_modules\npm\lib\cache\caching-client.js:174:7)
44 verbose stack     at \npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:261:18
44 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
46 error Windows_NT 6.1.7601
47 error argv "C:\\Program Files\\nodejs\\node.exe" "\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "ng2-image-cropper@0.7.6"
48 error node v6.11.1
49 error npm  v4.1.2
50 error code ETARGET
51 error notarget No compatible version found: ng2-image-cropper@0.7.6
51 error notarget Valid install targets:
51 error notarget 0.0.1, 0.0.2, 0.0.3
52 error notarget This is most likely not a problem with npm itself.
52 error notarget In most cases you or one of your dependencies are requesting
52 error notarget a package version that doesn't exist.
53 verbose exit [ 1, true ]
```

@cstefanache

**Comment by parker-mike** [comment]
@michael-fei It's quite simple, you're trying to get a wrong(?) package `ng2-image-cropper` instead of `ng2-img-cropper`, so maybe you should try `npm install ng2-img-cropper` to get the latest version, which currently is 0.9.0 or `npm install ng2-img-cropper@0.7.6` to get the version you were trying to get...

**Comment by web-dave** [comment]
this repo is deprecated. But this comp will be maintained by me at https://github.com/web-dave/ngx-img-cropper
